name: Kingdoms
version: '${project.version}'
main: me.tsjollin.kingdoms.Main
api-version: 1.19
authors: [ Tsjollin ]
description: Kingdom Plugin
commands:
  kingdom:
    description: Kingdom shit
    usage: /<command>
    aliases: k